### ISSUE TITLE
Whether the regularization of the objective function is incorrect

### ISSUE THREAD

**Issue by wangxiaodong1021** [cooperlab/SurvivalNet#33]
https://github.com/CancerDataScience/SurvivalNet/blob/83b99fffea15bca5f0017fa08bef61de9f165eea/survivalnet/model/Model.py#L197

Whether the regularization of the objective function is incorrect？

Whether the regularization item needs to be added instead of minus

**Comment by safooray** [comment]
Why do you think it's incorrect?

**Comment by wangxiaodong1021** [comment]
Shouldn't it be like this?

`self.risk_layer.cost(self.o, self.at_risk)+self.regularizers,`

**Comment by wangxiaodong1021** [comment]
Sorry, I understand the wrong, the cost here is to find the maximum. I understand the conventional loss function.
