### ISSUE TITLE
Cannot convert Type TensorType(float64, matrix) (of Variable X) into Type TensorType(float32, matrix). You can try to manually convert X into a TensorType(float32, matrix)

### ISSUE THREAD

**Issue by ankkoc22** [cooperlab/SurvivalNet#34]
Hi, I was trying to run the Model Analysis file after generating the final_model, but I am getting this error:
Cannot convert Type TensorType(float64, matrix) (of Variable X) into Type TensorType(float32, matrix). You can try to manually convert X into a TensorType(float32, matrix)

**Comment by ofonov** [comment]
I am getting the same error while using the Docker container, version 1.2. Could you please let me know how wast it fixed (which script needs to be fixed)? ModelAnalysis.py in Docker container version 1.2 and on GitHub are identical, therefore I suspect that the fix was implemented elsewhere.

**Comment by ankkoc22** [comment]
Use theano 0.8.2 instead of theano 1.0.0

**Comment by Nusha34** [comment]
Hi! I had the same issue and I solved it using your solution. But now I have issue with pickle which I didn't have before with 1.0.0 version. Did you have the same problem? 

   Model = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1083, in load_newobj
    obj = cls.__new__(cls, *args)
AttributeError: class scratchpad has no attribute '__new__'


> Use theano 0.8.2 instead of theano 1.0.0
